spring.application.name=Home-Schedules
spring.datasource.url=${database.url}
spring.datasource.username=${database.username}
spring.datasource.userpassword=${database.password}

spring.jpa.properties.hibernate,dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.dll-auto=update

