database.driver = org.postgresql.Driver
database.url = jdbc:postgresql://192.168.49.2:31711/postgres_bdd
database.username = root
database.password = admin
database.changelogfile = db.changelog-master.xml