database.driver = org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.userpassword=admin
database.changelogfile = db.changelog-master.xml